[2023-10-29T02:30:36.659+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:30:27.833018+00:00 [queued]>
[2023-10-29T02:30:36.666+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:30:27.833018+00:00 [queued]>
[2023-10-29T02:30:36.666+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-10-29T02:30:36.680+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): tsk_is_file_in_s3_available> on 2023-10-29 02:30:27.833018+00:00
[2023-10-29T02:30:36.683+0000] {standard_task_runner.py:57} INFO - Started process 1609 to run task
[2023-10-29T02:30:36.687+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'zillow_analytics_dag', 'tsk_is_file_in_s3_available', 'manual__2023-10-29T02:30:27.833018+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/analytics.py', '--cfg-path', '/tmp/tmpcitq49k7']
[2023-10-29T02:30:36.688+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask tsk_is_file_in_s3_available
[2023-10-29T02:30:36.723+0000] {task_command.py:416} INFO - Running <TaskInstance: zillow_analytics_dag.tsk_is_file_in_s3_available manual__2023-10-29T02:30:27.833018+00:00 [running]> on host ip-172-31-56-104.ec2.internal
[2023-10-29T02:30:36.787+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='chattisowmya@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='zillow_analytics_dag' AIRFLOW_CTX_TASK_ID='tsk_is_file_in_s3_available' AIRFLOW_CTX_EXECUTION_DATE='2023-10-29T02:30:27.833018+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-29T02:30:27.833018+00:00'
[2023-10-29T02:30:36.788+0000] {s3.py:106} INFO - Poking for key : s3://cleaned-data-zone-for-csv-bucket/response_data_29102023023029.csv
[2023-10-29T02:30:36.792+0000] {base.py:73} INFO - Using connection ID 'aws_s3_conn' for task execution.
[2023-10-29T02:30:36.793+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-10-29T02:30:42.161+0000] {s3.py:106} INFO - Poking for key : s3://cleaned-data-zone-for-csv-bucket/response_data_29102023023029.csv
[2023-10-29T02:30:47.177+0000] {s3.py:106} INFO - Poking for key : s3://cleaned-data-zone-for-csv-bucket/response_data_29102023023029.csv
[2023-10-29T02:30:47.191+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-29T02:30:47.196+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=zillow_analytics_dag, task_id=tsk_is_file_in_s3_available, execution_date=20231029T023027, start_date=20231029T023036, end_date=20231029T023047
[2023-10-29T02:30:47.222+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-29T02:30:47.240+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
